import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-mortgage-investor-claim-reimbursement-recovery",
  "engine": "recovery",
  "title": "Mortgage Investor Claim Reimbursement Recovery",
  "shortTitle": "Mortgage Investor Claim Reimbursement Recovery",
  "tagline": "Recover allowable default-servicing advances and expenses while preventing investor curtailments and deadline failures.",
  "industry": "Mortgage Servicing Finance",
  "buyer": "Mortgage servicers and subservicers",
  "uiPort": 4679,
  "apiPort": 5679,
  "accent": "#c2410c",
  "currency": "USD",
  "primaryOutcome": "Mortgage Investor Claim Reimbursement Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect investor guides, loan data, default milestones, property preservation, attorney fees, advances, conveyance, claim submissions, curtailments, and reimbursements in one accountable workflow. Recover allowable default-servicing advances and expenses while preventing investor curtailments and deadline failures.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Mortgage Investor Claim Reimbursement Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("investor-guide-library","MIC01","Investor guide library","Execute investor guide library using investor guides, loan data, default milestones, property preservation, attorney fees, advances, conveyance, claim submissions, curtailments, and reimbursements.","Produce a governed investor guide library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Defaulted Loan","text","Investor / Defaulted Loan · Standard Case"],["caseReference","Investor guide library Reference","text","MIC01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1002500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1213025],["domainDriver","Claim Program","select","FHA",["FHA","VA","USDA"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Investor guide library case","Default loan registry case","Milestone deadline control case","Property preservation expense case","Attorney fee validation case"]}),
feature("default-loan-registry","MIC02","Default loan registry","Execute default loan registry using investor guides, loan data, default milestones, property preservation, attorney fees, advances, conveyance, claim submissions, curtailments, and reimbursements.","Produce a governed default loan registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Defaulted Loan","text","Investor / Defaulted Loan · Standard Case"],["caseReference","Default loan registry Reference","text","MIC02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1002500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1213025],["domainDriver","Claim Program","select","FHA",["FHA","VA","USDA"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Investor guide library case","Default loan registry case","Milestone deadline control case","Property preservation expense case","Attorney fee validation case"]}),
feature("milestone-deadline-control","MIC03","Milestone deadline control","Execute milestone deadline control using investor guides, loan data, default milestones, property preservation, attorney fees, advances, conveyance, claim submissions, curtailments, and reimbursements.","Produce a governed milestone deadline control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Defaulted Loan","text","Investor / Defaulted Loan · Standard Case"],["caseReference","Milestone deadline control Reference","text","MIC03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1002500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1213025],["domainDriver","Claim Program","select","FHA",["FHA","VA","USDA"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Investor guide library case","Default loan registry case","Milestone deadline control case","Property preservation expense case","Attorney fee validation case"]}),
feature("property-preservation-expense","MIC04","Property preservation expense","Execute property preservation expense using investor guides, loan data, default milestones, property preservation, attorney fees, advances, conveyance, claim submissions, curtailments, and reimbursements.","Produce a governed property preservation expense decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Defaulted Loan","text","Investor / Defaulted Loan · Standard Case"],["caseReference","Property preservation expense Reference","text","MIC04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1002500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1213025],["domainDriver","Claim Program","select","FHA",["FHA","VA","USDA"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Investor guide library case","Default loan registry case","Milestone deadline control case","Property preservation expense case","Attorney fee validation case"]}),
feature("attorney-fee-validation","MIC05","Attorney fee validation","Execute attorney fee validation using investor guides, loan data, default milestones, property preservation, attorney fees, advances, conveyance, claim submissions, curtailments, and reimbursements.","Produce a governed attorney fee validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Defaulted Loan","text","Investor / Defaulted Loan · Standard Case"],["caseReference","Attorney fee validation Reference","text","MIC05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1002500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1213025],["domainDriver","Claim Program","select","FHA",["FHA","VA","USDA"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Investor guide library case","Default loan registry case","Milestone deadline control case","Property preservation expense case","Attorney fee validation case"]}),
feature("tax-insurance-advances","MIC06","Tax insurance advances","Execute tax insurance advances using investor guides, loan data, default milestones, property preservation, attorney fees, advances, conveyance, claim submissions, curtailments, and reimbursements.","Produce a governed tax insurance advances decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Defaulted Loan","text","Investor / Defaulted Loan · Standard Case"],["caseReference","Tax insurance advances Reference","text","MIC06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1002500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1213025],["domainDriver","Claim Program","select","FHA",["FHA","VA","USDA"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Investor guide library case","Default loan registry case","Milestone deadline control case","Property preservation expense case","Attorney fee validation case"]}),
feature("conveyance-condition-tracking","MIC07","Conveyance condition tracking","Execute conveyance condition tracking using investor guides, loan data, default milestones, property preservation, attorney fees, advances, conveyance, claim submissions, curtailments, and reimbursements.","Produce a governed conveyance condition tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Defaulted Loan","text","Investor / Defaulted Loan · Standard Case"],["caseReference","Conveyance condition tracking Reference","text","MIC07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1002500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1213025],["domainDriver","Claim Program","select","FHA",["FHA","VA","USDA"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Investor guide library case","Default loan registry case","Milestone deadline control case","Property preservation expense case","Attorney fee validation case"]}),
feature("claimable-expense-classification","MIC08","Claimable expense classification","Execute claimable expense classification using investor guides, loan data, default milestones, property preservation, attorney fees, advances, conveyance, claim submissions, curtailments, and reimbursements.","Produce a governed claimable expense classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Defaulted Loan","text","Investor / Defaulted Loan · Standard Case"],["caseReference","Claimable expense classification Reference","text","MIC08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1002500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1213025],["domainDriver","Claim Program","select","FHA",["FHA","VA","USDA"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Investor guide library case","Default loan registry case","Milestone deadline control case","Property preservation expense case","Attorney fee validation case"]}),
feature("interest-curtailment-calculation","MIC09","Interest curtailment calculation","Execute interest curtailment calculation using investor guides, loan data, default milestones, property preservation, attorney fees, advances, conveyance, claim submissions, curtailments, and reimbursements.","Produce a governed interest curtailment calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Defaulted Loan","text","Investor / Defaulted Loan · Standard Case"],["caseReference","Interest curtailment calculation Reference","text","MIC09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1002500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1213025],["domainDriver","Claim Program","select","FHA",["FHA","VA","USDA"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Investor guide library case","Default loan registry case","Milestone deadline control case","Property preservation expense case","Attorney fee validation case"]}),
feature("claim-form-preparation","MIC10","Claim form preparation","Execute claim form preparation using investor guides, loan data, default milestones, property preservation, attorney fees, advances, conveyance, claim submissions, curtailments, and reimbursements.","Produce a governed claim form preparation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Defaulted Loan","text","Investor / Defaulted Loan · Standard Case"],["caseReference","Claim form preparation Reference","text","MIC10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1002500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1213025],["domainDriver","Claim Program","select","FHA",["FHA","VA","USDA"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Investor guide library case","Default loan registry case","Milestone deadline control case","Property preservation expense case","Attorney fee validation case"]}),
feature("investor-exception-remediation","MIC11","Investor exception remediation","Execute investor exception remediation using investor guides, loan data, default milestones, property preservation, attorney fees, advances, conveyance, claim submissions, curtailments, and reimbursements.","Produce a governed investor exception remediation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Defaulted Loan","text","Investor / Defaulted Loan · Standard Case"],["caseReference","Investor exception remediation Reference","text","MIC11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1002500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1213025],["domainDriver","Claim Program","select","FHA",["FHA","VA","USDA"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Investor guide library case","Default loan registry case","Milestone deadline control case","Property preservation expense case","Attorney fee validation case"]}),
feature("supplemental-claim-workflow","MIC12","Supplemental claim workflow","Execute supplemental claim workflow using investor guides, loan data, default milestones, property preservation, attorney fees, advances, conveyance, claim submissions, curtailments, and reimbursements.","Produce a governed supplemental claim workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Defaulted Loan","text","Investor / Defaulted Loan · Standard Case"],["caseReference","Supplemental claim workflow Reference","text","MIC12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1002500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1213025],["domainDriver","Claim Program","select","FHA",["FHA","VA","USDA"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Investor guide library case","Default loan registry case","Milestone deadline control case","Property preservation expense case","Attorney fee validation case"]}),
feature("reimbursement-matching","MIC13","Reimbursement matching","Execute reimbursement matching using investor guides, loan data, default milestones, property preservation, attorney fees, advances, conveyance, claim submissions, curtailments, and reimbursements.","Produce a governed reimbursement matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Defaulted Loan","text","Investor / Defaulted Loan · Standard Case"],["caseReference","Reimbursement matching Reference","text","MIC13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1002500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1213025],["domainDriver","Claim Program","select","FHA",["FHA","VA","USDA"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Investor guide library case","Default loan registry case","Milestone deadline control case","Property preservation expense case","Attorney fee validation case"]}),
feature("unrecovered-advance-ledger","MIC14","Unrecovered advance ledger","Execute unrecovered advance ledger using investor guides, loan data, default milestones, property preservation, attorney fees, advances, conveyance, claim submissions, curtailments, and reimbursements.","Produce a governed unrecovered advance ledger decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Defaulted Loan","text","Investor / Defaulted Loan · Standard Case"],["caseReference","Unrecovered advance ledger Reference","text","MIC14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1002500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1213025],["domainDriver","Claim Program","select","FHA",["FHA","VA","USDA"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Investor guide library case","Default loan registry case","Milestone deadline control case","Property preservation expense case","Attorney fee validation case"]}),
feature("investor-vendor-analytics","MIC15","Investor vendor analytics","Execute investor vendor analytics using investor guides, loan data, default milestones, property preservation, attorney fees, advances, conveyance, claim submissions, curtailments, and reimbursements.","Produce a governed investor vendor analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Investor / Defaulted Loan","text","Investor / Defaulted Loan · Standard Case"],["caseReference","Investor vendor analytics Reference","text","MIC15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1002500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1213025],["domainDriver","Claim Program","select","FHA",["FHA","VA","USDA"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Investor guide library case","Default loan registry case","Milestone deadline control case","Property preservation expense case","Attorney fee validation case"]})
]);
